# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontribuyente',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='código'),
        ),
    ]
