# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20180525_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=15, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_contribuyente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.TipoContribuyente', verbose_name='Tipo contribuyente'),
        ),
    ]
